-- WHC Matrix Schema
-- Creates tables for 258 World Heritage Cities environmental signature matrix
-- Run with: psql -h localhost -p 5435 -U postgres -d edop < sql/whc_matrix_schema.sql
--
-- Prerequisites: wh_cities table must exist with id, geom, basin_id columns

-- Drop existing tables if they exist (in reverse dependency order)
DROP TABLE IF EXISTS whc_similarity CASCADE;
DROP TABLE IF EXISTS whc_clusters CASCADE;
DROP TABLE IF EXISTS whc_pca_coords CASCADE;
DROP TABLE IF EXISTS whc_pca_variance CASCADE;
DROP TABLE IF EXISTS whc_matrix CASCADE;

--------------------------------------------------------------------------------
-- 1. Wide matrix table (same structure as edop_matrix but references wh_cities)
-- Columns: city_id + 27 numerical + 15 pnv + 1519 categorical = 1562 columns
--------------------------------------------------------------------------------
CREATE TABLE whc_matrix (
    city_id INTEGER PRIMARY KEY REFERENCES wh_cities(id),

    -- ========================================================================
    -- NUMERICAL FIELDS (27) - normalized 0-1 based on global min/max
    -- ========================================================================

    -- A: Physiographic Bedrock (7)
    n_elev_min DOUBLE PRECISION,
    n_elev_max DOUBLE PRECISION,
    n_slope_avg DOUBLE PRECISION,
    n_slope_upstream DOUBLE PRECISION,
    n_stream_gradient DOUBLE PRECISION,
    n_karst DOUBLE PRECISION,
    n_karst_upstream DOUBLE PRECISION,

    -- B: Hydro-Climatic Baselines (10)
    n_discharge_yr DOUBLE PRECISION,
    n_discharge_min DOUBLE PRECISION,
    n_discharge_max DOUBLE PRECISION,
    n_river_area DOUBLE PRECISION,
    n_river_area_upstream DOUBLE PRECISION,
    n_runoff DOUBLE PRECISION,
    n_gw_table_depth DOUBLE PRECISION,
    n_pct_clay DOUBLE PRECISION,
    n_pct_silt DOUBLE PRECISION,
    n_pct_sand DOUBLE PRECISION,

    -- C: Bioclimatic Proxies (8)
    n_temp_yr DOUBLE PRECISION,
    n_temp_min DOUBLE PRECISION,
    n_temp_max DOUBLE PRECISION,
    n_precip_yr DOUBLE PRECISION,
    n_aridity DOUBLE PRECISION,
    n_wet_pct_grp1 DOUBLE PRECISION,
    n_wet_pct_grp2 DOUBLE PRECISION,
    n_permafrost_extent DOUBLE PRECISION,

    -- D: Anthropocene Markers (6)
    n_reservoir_vol DOUBLE PRECISION,
    n_cropland_extent DOUBLE PRECISION,
    n_pop_density DOUBLE PRECISION,
    n_human_footprint_09 DOUBLE PRECISION,
    n_gdp_avg DOUBLE PRECISION,
    n_human_dev_idx DOUBLE PRECISION,

    -- ========================================================================
    -- PNV SHARES (15) - continuous 0-1 (rescaled from 0-100)
    -- ========================================================================
    pnv_01 DOUBLE PRECISION DEFAULT 0,
    pnv_02 DOUBLE PRECISION DEFAULT 0,
    pnv_03 DOUBLE PRECISION DEFAULT 0,
    pnv_04 DOUBLE PRECISION DEFAULT 0,
    pnv_05 DOUBLE PRECISION DEFAULT 0,
    pnv_06 DOUBLE PRECISION DEFAULT 0,
    pnv_07 DOUBLE PRECISION DEFAULT 0,
    pnv_08 DOUBLE PRECISION DEFAULT 0,
    pnv_09 DOUBLE PRECISION DEFAULT 0,
    pnv_10 DOUBLE PRECISION DEFAULT 0,
    pnv_11 DOUBLE PRECISION DEFAULT 0,
    pnv_12 DOUBLE PRECISION DEFAULT 0,
    pnv_13 DOUBLE PRECISION DEFAULT 0,
    pnv_14 DOUBLE PRECISION DEFAULT 0,
    pnv_15 DOUBLE PRECISION DEFAULT 0,

    -- ========================================================================
    -- CATEGORICAL ONE-HOT COLUMNS (1519)
    -- Same structure as edop_matrix - generated dynamically
    -- ========================================================================

    -- lu_tec: Terrestrial Ecoregions (847 columns, eco_id 0-846)
    cat_tec_0 SMALLINT DEFAULT 0, cat_tec_1 SMALLINT DEFAULT 0, cat_tec_2 SMALLINT DEFAULT 0, cat_tec_3 SMALLINT DEFAULT 0, cat_tec_4 SMALLINT DEFAULT 0,
    cat_tec_5 SMALLINT DEFAULT 0, cat_tec_6 SMALLINT DEFAULT 0, cat_tec_7 SMALLINT DEFAULT 0, cat_tec_8 SMALLINT DEFAULT 0, cat_tec_9 SMALLINT DEFAULT 0,
    cat_tec_10 SMALLINT DEFAULT 0, cat_tec_11 SMALLINT DEFAULT 0, cat_tec_12 SMALLINT DEFAULT 0, cat_tec_13 SMALLINT DEFAULT 0, cat_tec_14 SMALLINT DEFAULT 0,
    cat_tec_15 SMALLINT DEFAULT 0, cat_tec_16 SMALLINT DEFAULT 0, cat_tec_17 SMALLINT DEFAULT 0, cat_tec_18 SMALLINT DEFAULT 0, cat_tec_19 SMALLINT DEFAULT 0,
    cat_tec_20 SMALLINT DEFAULT 0, cat_tec_21 SMALLINT DEFAULT 0, cat_tec_22 SMALLINT DEFAULT 0, cat_tec_23 SMALLINT DEFAULT 0, cat_tec_24 SMALLINT DEFAULT 0,
    cat_tec_25 SMALLINT DEFAULT 0, cat_tec_26 SMALLINT DEFAULT 0, cat_tec_27 SMALLINT DEFAULT 0, cat_tec_28 SMALLINT DEFAULT 0, cat_tec_29 SMALLINT DEFAULT 0,
    cat_tec_30 SMALLINT DEFAULT 0, cat_tec_31 SMALLINT DEFAULT 0, cat_tec_32 SMALLINT DEFAULT 0, cat_tec_33 SMALLINT DEFAULT 0, cat_tec_34 SMALLINT DEFAULT 0,
    cat_tec_35 SMALLINT DEFAULT 0, cat_tec_36 SMALLINT DEFAULT 0, cat_tec_37 SMALLINT DEFAULT 0, cat_tec_38 SMALLINT DEFAULT 0, cat_tec_39 SMALLINT DEFAULT 0,
    cat_tec_40 SMALLINT DEFAULT 0, cat_tec_41 SMALLINT DEFAULT 0, cat_tec_42 SMALLINT DEFAULT 0, cat_tec_43 SMALLINT DEFAULT 0, cat_tec_44 SMALLINT DEFAULT 0,
    cat_tec_45 SMALLINT DEFAULT 0, cat_tec_46 SMALLINT DEFAULT 0, cat_tec_47 SMALLINT DEFAULT 0, cat_tec_48 SMALLINT DEFAULT 0, cat_tec_49 SMALLINT DEFAULT 0,
    cat_tec_50 SMALLINT DEFAULT 0, cat_tec_51 SMALLINT DEFAULT 0, cat_tec_52 SMALLINT DEFAULT 0, cat_tec_53 SMALLINT DEFAULT 0, cat_tec_54 SMALLINT DEFAULT 0,
    cat_tec_55 SMALLINT DEFAULT 0, cat_tec_56 SMALLINT DEFAULT 0, cat_tec_57 SMALLINT DEFAULT 0, cat_tec_58 SMALLINT DEFAULT 0, cat_tec_59 SMALLINT DEFAULT 0,
    cat_tec_60 SMALLINT DEFAULT 0, cat_tec_61 SMALLINT DEFAULT 0, cat_tec_62 SMALLINT DEFAULT 0, cat_tec_63 SMALLINT DEFAULT 0, cat_tec_64 SMALLINT DEFAULT 0,
    cat_tec_65 SMALLINT DEFAULT 0, cat_tec_66 SMALLINT DEFAULT 0, cat_tec_67 SMALLINT DEFAULT 0, cat_tec_68 SMALLINT DEFAULT 0, cat_tec_69 SMALLINT DEFAULT 0,
    cat_tec_70 SMALLINT DEFAULT 0, cat_tec_71 SMALLINT DEFAULT 0, cat_tec_72 SMALLINT DEFAULT 0, cat_tec_73 SMALLINT DEFAULT 0, cat_tec_74 SMALLINT DEFAULT 0,
    cat_tec_75 SMALLINT DEFAULT 0, cat_tec_76 SMALLINT DEFAULT 0, cat_tec_77 SMALLINT DEFAULT 0, cat_tec_78 SMALLINT DEFAULT 0, cat_tec_79 SMALLINT DEFAULT 0,
    cat_tec_80 SMALLINT DEFAULT 0, cat_tec_81 SMALLINT DEFAULT 0, cat_tec_82 SMALLINT DEFAULT 0, cat_tec_83 SMALLINT DEFAULT 0, cat_tec_84 SMALLINT DEFAULT 0,
    cat_tec_85 SMALLINT DEFAULT 0, cat_tec_86 SMALLINT DEFAULT 0, cat_tec_87 SMALLINT DEFAULT 0, cat_tec_88 SMALLINT DEFAULT 0, cat_tec_89 SMALLINT DEFAULT 0,
    cat_tec_90 SMALLINT DEFAULT 0, cat_tec_91 SMALLINT DEFAULT 0, cat_tec_92 SMALLINT DEFAULT 0, cat_tec_93 SMALLINT DEFAULT 0, cat_tec_94 SMALLINT DEFAULT 0,
    cat_tec_95 SMALLINT DEFAULT 0, cat_tec_96 SMALLINT DEFAULT 0, cat_tec_97 SMALLINT DEFAULT 0, cat_tec_98 SMALLINT DEFAULT 0, cat_tec_99 SMALLINT DEFAULT 0,
    cat_tec_100 SMALLINT DEFAULT 0, cat_tec_101 SMALLINT DEFAULT 0, cat_tec_102 SMALLINT DEFAULT 0, cat_tec_103 SMALLINT DEFAULT 0, cat_tec_104 SMALLINT DEFAULT 0,
    cat_tec_105 SMALLINT DEFAULT 0, cat_tec_106 SMALLINT DEFAULT 0, cat_tec_107 SMALLINT DEFAULT 0, cat_tec_108 SMALLINT DEFAULT 0, cat_tec_109 SMALLINT DEFAULT 0,
    cat_tec_110 SMALLINT DEFAULT 0, cat_tec_111 SMALLINT DEFAULT 0, cat_tec_112 SMALLINT DEFAULT 0, cat_tec_113 SMALLINT DEFAULT 0, cat_tec_114 SMALLINT DEFAULT 0,
    cat_tec_115 SMALLINT DEFAULT 0, cat_tec_116 SMALLINT DEFAULT 0, cat_tec_117 SMALLINT DEFAULT 0, cat_tec_118 SMALLINT DEFAULT 0, cat_tec_119 SMALLINT DEFAULT 0,
    cat_tec_120 SMALLINT DEFAULT 0, cat_tec_121 SMALLINT DEFAULT 0, cat_tec_122 SMALLINT DEFAULT 0, cat_tec_123 SMALLINT DEFAULT 0, cat_tec_124 SMALLINT DEFAULT 0,
    cat_tec_125 SMALLINT DEFAULT 0, cat_tec_126 SMALLINT DEFAULT 0, cat_tec_127 SMALLINT DEFAULT 0, cat_tec_128 SMALLINT DEFAULT 0, cat_tec_129 SMALLINT DEFAULT 0,
    cat_tec_130 SMALLINT DEFAULT 0, cat_tec_131 SMALLINT DEFAULT 0, cat_tec_132 SMALLINT DEFAULT 0, cat_tec_133 SMALLINT DEFAULT 0, cat_tec_134 SMALLINT DEFAULT 0,
    cat_tec_135 SMALLINT DEFAULT 0, cat_tec_136 SMALLINT DEFAULT 0, cat_tec_137 SMALLINT DEFAULT 0, cat_tec_138 SMALLINT DEFAULT 0, cat_tec_139 SMALLINT DEFAULT 0,
    cat_tec_140 SMALLINT DEFAULT 0, cat_tec_141 SMALLINT DEFAULT 0, cat_tec_142 SMALLINT DEFAULT 0, cat_tec_143 SMALLINT DEFAULT 0, cat_tec_144 SMALLINT DEFAULT 0,
    cat_tec_145 SMALLINT DEFAULT 0, cat_tec_146 SMALLINT DEFAULT 0, cat_tec_147 SMALLINT DEFAULT 0, cat_tec_148 SMALLINT DEFAULT 0, cat_tec_149 SMALLINT DEFAULT 0,
    cat_tec_150 SMALLINT DEFAULT 0, cat_tec_151 SMALLINT DEFAULT 0, cat_tec_152 SMALLINT DEFAULT 0, cat_tec_153 SMALLINT DEFAULT 0, cat_tec_154 SMALLINT DEFAULT 0,
    cat_tec_155 SMALLINT DEFAULT 0, cat_tec_156 SMALLINT DEFAULT 0, cat_tec_157 SMALLINT DEFAULT 0, cat_tec_158 SMALLINT DEFAULT 0, cat_tec_159 SMALLINT DEFAULT 0,
    cat_tec_160 SMALLINT DEFAULT 0, cat_tec_161 SMALLINT DEFAULT 0, cat_tec_162 SMALLINT DEFAULT 0, cat_tec_163 SMALLINT DEFAULT 0, cat_tec_164 SMALLINT DEFAULT 0,
    cat_tec_165 SMALLINT DEFAULT 0, cat_tec_166 SMALLINT DEFAULT 0, cat_tec_167 SMALLINT DEFAULT 0, cat_tec_168 SMALLINT DEFAULT 0, cat_tec_169 SMALLINT DEFAULT 0,
    cat_tec_170 SMALLINT DEFAULT 0, cat_tec_171 SMALLINT DEFAULT 0, cat_tec_172 SMALLINT DEFAULT 0, cat_tec_173 SMALLINT DEFAULT 0, cat_tec_174 SMALLINT DEFAULT 0,
    cat_tec_175 SMALLINT DEFAULT 0, cat_tec_176 SMALLINT DEFAULT 0, cat_tec_177 SMALLINT DEFAULT 0, cat_tec_178 SMALLINT DEFAULT 0, cat_tec_179 SMALLINT DEFAULT 0,
    cat_tec_180 SMALLINT DEFAULT 0, cat_tec_181 SMALLINT DEFAULT 0, cat_tec_182 SMALLINT DEFAULT 0, cat_tec_183 SMALLINT DEFAULT 0, cat_tec_184 SMALLINT DEFAULT 0,
    cat_tec_185 SMALLINT DEFAULT 0, cat_tec_186 SMALLINT DEFAULT 0, cat_tec_187 SMALLINT DEFAULT 0, cat_tec_188 SMALLINT DEFAULT 0, cat_tec_189 SMALLINT DEFAULT 0,
    cat_tec_190 SMALLINT DEFAULT 0, cat_tec_191 SMALLINT DEFAULT 0, cat_tec_192 SMALLINT DEFAULT 0, cat_tec_193 SMALLINT DEFAULT 0, cat_tec_194 SMALLINT DEFAULT 0,
    cat_tec_195 SMALLINT DEFAULT 0, cat_tec_196 SMALLINT DEFAULT 0, cat_tec_197 SMALLINT DEFAULT 0, cat_tec_198 SMALLINT DEFAULT 0, cat_tec_199 SMALLINT DEFAULT 0,
    cat_tec_200 SMALLINT DEFAULT 0, cat_tec_201 SMALLINT DEFAULT 0, cat_tec_202 SMALLINT DEFAULT 0, cat_tec_203 SMALLINT DEFAULT 0, cat_tec_204 SMALLINT DEFAULT 0,
    cat_tec_205 SMALLINT DEFAULT 0, cat_tec_206 SMALLINT DEFAULT 0, cat_tec_207 SMALLINT DEFAULT 0, cat_tec_208 SMALLINT DEFAULT 0, cat_tec_209 SMALLINT DEFAULT 0,
    cat_tec_210 SMALLINT DEFAULT 0, cat_tec_211 SMALLINT DEFAULT 0, cat_tec_212 SMALLINT DEFAULT 0, cat_tec_213 SMALLINT DEFAULT 0, cat_tec_214 SMALLINT DEFAULT 0,
    cat_tec_215 SMALLINT DEFAULT 0, cat_tec_216 SMALLINT DEFAULT 0, cat_tec_217 SMALLINT DEFAULT 0, cat_tec_218 SMALLINT DEFAULT 0, cat_tec_219 SMALLINT DEFAULT 0,
    cat_tec_220 SMALLINT DEFAULT 0, cat_tec_221 SMALLINT DEFAULT 0, cat_tec_222 SMALLINT DEFAULT 0, cat_tec_223 SMALLINT DEFAULT 0, cat_tec_224 SMALLINT DEFAULT 0,
    cat_tec_225 SMALLINT DEFAULT 0, cat_tec_226 SMALLINT DEFAULT 0, cat_tec_227 SMALLINT DEFAULT 0, cat_tec_228 SMALLINT DEFAULT 0, cat_tec_229 SMALLINT DEFAULT 0,
    cat_tec_230 SMALLINT DEFAULT 0, cat_tec_231 SMALLINT DEFAULT 0, cat_tec_232 SMALLINT DEFAULT 0, cat_tec_233 SMALLINT DEFAULT 0, cat_tec_234 SMALLINT DEFAULT 0,
    cat_tec_235 SMALLINT DEFAULT 0, cat_tec_236 SMALLINT DEFAULT 0, cat_tec_237 SMALLINT DEFAULT 0, cat_tec_238 SMALLINT DEFAULT 0, cat_tec_239 SMALLINT DEFAULT 0,
    cat_tec_240 SMALLINT DEFAULT 0, cat_tec_241 SMALLINT DEFAULT 0, cat_tec_242 SMALLINT DEFAULT 0, cat_tec_243 SMALLINT DEFAULT 0, cat_tec_244 SMALLINT DEFAULT 0,
    cat_tec_245 SMALLINT DEFAULT 0, cat_tec_246 SMALLINT DEFAULT 0, cat_tec_247 SMALLINT DEFAULT 0, cat_tec_248 SMALLINT DEFAULT 0, cat_tec_249 SMALLINT DEFAULT 0,
    cat_tec_250 SMALLINT DEFAULT 0, cat_tec_251 SMALLINT DEFAULT 0, cat_tec_252 SMALLINT DEFAULT 0, cat_tec_253 SMALLINT DEFAULT 0, cat_tec_254 SMALLINT DEFAULT 0,
    cat_tec_255 SMALLINT DEFAULT 0, cat_tec_256 SMALLINT DEFAULT 0, cat_tec_257 SMALLINT DEFAULT 0, cat_tec_258 SMALLINT DEFAULT 0, cat_tec_259 SMALLINT DEFAULT 0,
    cat_tec_260 SMALLINT DEFAULT 0, cat_tec_261 SMALLINT DEFAULT 0, cat_tec_262 SMALLINT DEFAULT 0, cat_tec_263 SMALLINT DEFAULT 0, cat_tec_264 SMALLINT DEFAULT 0,
    cat_tec_265 SMALLINT DEFAULT 0, cat_tec_266 SMALLINT DEFAULT 0, cat_tec_267 SMALLINT DEFAULT 0, cat_tec_268 SMALLINT DEFAULT 0, cat_tec_269 SMALLINT DEFAULT 0,
    cat_tec_270 SMALLINT DEFAULT 0, cat_tec_271 SMALLINT DEFAULT 0, cat_tec_272 SMALLINT DEFAULT 0, cat_tec_273 SMALLINT DEFAULT 0, cat_tec_274 SMALLINT DEFAULT 0,
    cat_tec_275 SMALLINT DEFAULT 0, cat_tec_276 SMALLINT DEFAULT 0, cat_tec_277 SMALLINT DEFAULT 0, cat_tec_278 SMALLINT DEFAULT 0, cat_tec_279 SMALLINT DEFAULT 0,
    cat_tec_280 SMALLINT DEFAULT 0, cat_tec_281 SMALLINT DEFAULT 0, cat_tec_282 SMALLINT DEFAULT 0, cat_tec_283 SMALLINT DEFAULT 0, cat_tec_284 SMALLINT DEFAULT 0,
    cat_tec_285 SMALLINT DEFAULT 0, cat_tec_286 SMALLINT DEFAULT 0, cat_tec_287 SMALLINT DEFAULT 0, cat_tec_288 SMALLINT DEFAULT 0, cat_tec_289 SMALLINT DEFAULT 0,
    cat_tec_290 SMALLINT DEFAULT 0, cat_tec_291 SMALLINT DEFAULT 0, cat_tec_292 SMALLINT DEFAULT 0, cat_tec_293 SMALLINT DEFAULT 0, cat_tec_294 SMALLINT DEFAULT 0,
    cat_tec_295 SMALLINT DEFAULT 0, cat_tec_296 SMALLINT DEFAULT 0, cat_tec_297 SMALLINT DEFAULT 0, cat_tec_298 SMALLINT DEFAULT 0, cat_tec_299 SMALLINT DEFAULT 0,
    cat_tec_300 SMALLINT DEFAULT 0, cat_tec_301 SMALLINT DEFAULT 0, cat_tec_302 SMALLINT DEFAULT 0, cat_tec_303 SMALLINT DEFAULT 0, cat_tec_304 SMALLINT DEFAULT 0,
    cat_tec_305 SMALLINT DEFAULT 0, cat_tec_306 SMALLINT DEFAULT 0, cat_tec_307 SMALLINT DEFAULT 0, cat_tec_308 SMALLINT DEFAULT 0, cat_tec_309 SMALLINT DEFAULT 0,
    cat_tec_310 SMALLINT DEFAULT 0, cat_tec_311 SMALLINT DEFAULT 0, cat_tec_312 SMALLINT DEFAULT 0, cat_tec_313 SMALLINT DEFAULT 0, cat_tec_314 SMALLINT DEFAULT 0,
    cat_tec_315 SMALLINT DEFAULT 0, cat_tec_316 SMALLINT DEFAULT 0, cat_tec_317 SMALLINT DEFAULT 0, cat_tec_318 SMALLINT DEFAULT 0, cat_tec_319 SMALLINT DEFAULT 0,
    cat_tec_320 SMALLINT DEFAULT 0, cat_tec_321 SMALLINT DEFAULT 0, cat_tec_322 SMALLINT DEFAULT 0, cat_tec_323 SMALLINT DEFAULT 0, cat_tec_324 SMALLINT DEFAULT 0,
    cat_tec_325 SMALLINT DEFAULT 0, cat_tec_326 SMALLINT DEFAULT 0, cat_tec_327 SMALLINT DEFAULT 0, cat_tec_328 SMALLINT DEFAULT 0, cat_tec_329 SMALLINT DEFAULT 0,
    cat_tec_330 SMALLINT DEFAULT 0, cat_tec_331 SMALLINT DEFAULT 0, cat_tec_332 SMALLINT DEFAULT 0, cat_tec_333 SMALLINT DEFAULT 0, cat_tec_334 SMALLINT DEFAULT 0,
    cat_tec_335 SMALLINT DEFAULT 0, cat_tec_336 SMALLINT DEFAULT 0, cat_tec_337 SMALLINT DEFAULT 0, cat_tec_338 SMALLINT DEFAULT 0, cat_tec_339 SMALLINT DEFAULT 0,
    cat_tec_340 SMALLINT DEFAULT 0, cat_tec_341 SMALLINT DEFAULT 0, cat_tec_342 SMALLINT DEFAULT 0, cat_tec_343 SMALLINT DEFAULT 0, cat_tec_344 SMALLINT DEFAULT 0,
    cat_tec_345 SMALLINT DEFAULT 0, cat_tec_346 SMALLINT DEFAULT 0, cat_tec_347 SMALLINT DEFAULT 0, cat_tec_348 SMALLINT DEFAULT 0, cat_tec_349 SMALLINT DEFAULT 0,
    cat_tec_350 SMALLINT DEFAULT 0, cat_tec_351 SMALLINT DEFAULT 0, cat_tec_352 SMALLINT DEFAULT 0, cat_tec_353 SMALLINT DEFAULT 0, cat_tec_354 SMALLINT DEFAULT 0,
    cat_tec_355 SMALLINT DEFAULT 0, cat_tec_356 SMALLINT DEFAULT 0, cat_tec_357 SMALLINT DEFAULT 0, cat_tec_358 SMALLINT DEFAULT 0, cat_tec_359 SMALLINT DEFAULT 0,
    cat_tec_360 SMALLINT DEFAULT 0, cat_tec_361 SMALLINT DEFAULT 0, cat_tec_362 SMALLINT DEFAULT 0, cat_tec_363 SMALLINT DEFAULT 0, cat_tec_364 SMALLINT DEFAULT 0,
    cat_tec_365 SMALLINT DEFAULT 0, cat_tec_366 SMALLINT DEFAULT 0, cat_tec_367 SMALLINT DEFAULT 0, cat_tec_368 SMALLINT DEFAULT 0, cat_tec_369 SMALLINT DEFAULT 0,
    cat_tec_370 SMALLINT DEFAULT 0, cat_tec_371 SMALLINT DEFAULT 0, cat_tec_372 SMALLINT DEFAULT 0, cat_tec_373 SMALLINT DEFAULT 0, cat_tec_374 SMALLINT DEFAULT 0,
    cat_tec_375 SMALLINT DEFAULT 0, cat_tec_376 SMALLINT DEFAULT 0, cat_tec_377 SMALLINT DEFAULT 0, cat_tec_378 SMALLINT DEFAULT 0, cat_tec_379 SMALLINT DEFAULT 0,
    cat_tec_380 SMALLINT DEFAULT 0, cat_tec_381 SMALLINT DEFAULT 0, cat_tec_382 SMALLINT DEFAULT 0, cat_tec_383 SMALLINT DEFAULT 0, cat_tec_384 SMALLINT DEFAULT 0,
    cat_tec_385 SMALLINT DEFAULT 0, cat_tec_386 SMALLINT DEFAULT 0, cat_tec_387 SMALLINT DEFAULT 0, cat_tec_388 SMALLINT DEFAULT 0, cat_tec_389 SMALLINT DEFAULT 0,
    cat_tec_390 SMALLINT DEFAULT 0, cat_tec_391 SMALLINT DEFAULT 0, cat_tec_392 SMALLINT DEFAULT 0, cat_tec_393 SMALLINT DEFAULT 0, cat_tec_394 SMALLINT DEFAULT 0,
    cat_tec_395 SMALLINT DEFAULT 0, cat_tec_396 SMALLINT DEFAULT 0, cat_tec_397 SMALLINT DEFAULT 0, cat_tec_398 SMALLINT DEFAULT 0, cat_tec_399 SMALLINT DEFAULT 0,
    cat_tec_400 SMALLINT DEFAULT 0, cat_tec_401 SMALLINT DEFAULT 0, cat_tec_402 SMALLINT DEFAULT 0, cat_tec_403 SMALLINT DEFAULT 0, cat_tec_404 SMALLINT DEFAULT 0,
    cat_tec_405 SMALLINT DEFAULT 0, cat_tec_406 SMALLINT DEFAULT 0, cat_tec_407 SMALLINT DEFAULT 0, cat_tec_408 SMALLINT DEFAULT 0, cat_tec_409 SMALLINT DEFAULT 0,
    cat_tec_410 SMALLINT DEFAULT 0, cat_tec_411 SMALLINT DEFAULT 0, cat_tec_412 SMALLINT DEFAULT 0, cat_tec_413 SMALLINT DEFAULT 0, cat_tec_414 SMALLINT DEFAULT 0,
    cat_tec_415 SMALLINT DEFAULT 0, cat_tec_416 SMALLINT DEFAULT 0, cat_tec_417 SMALLINT DEFAULT 0, cat_tec_418 SMALLINT DEFAULT 0, cat_tec_419 SMALLINT DEFAULT 0,
    cat_tec_420 SMALLINT DEFAULT 0, cat_tec_421 SMALLINT DEFAULT 0, cat_tec_422 SMALLINT DEFAULT 0, cat_tec_423 SMALLINT DEFAULT 0, cat_tec_424 SMALLINT DEFAULT 0,
    cat_tec_425 SMALLINT DEFAULT 0, cat_tec_426 SMALLINT DEFAULT 0, cat_tec_427 SMALLINT DEFAULT 0, cat_tec_428 SMALLINT DEFAULT 0, cat_tec_429 SMALLINT DEFAULT 0,
    cat_tec_430 SMALLINT DEFAULT 0, cat_tec_431 SMALLINT DEFAULT 0, cat_tec_432 SMALLINT DEFAULT 0, cat_tec_433 SMALLINT DEFAULT 0, cat_tec_434 SMALLINT DEFAULT 0,
    cat_tec_435 SMALLINT DEFAULT 0, cat_tec_436 SMALLINT DEFAULT 0, cat_tec_437 SMALLINT DEFAULT 0, cat_tec_438 SMALLINT DEFAULT 0, cat_tec_439 SMALLINT DEFAULT 0,
    cat_tec_440 SMALLINT DEFAULT 0, cat_tec_441 SMALLINT DEFAULT 0, cat_tec_442 SMALLINT DEFAULT 0, cat_tec_443 SMALLINT DEFAULT 0, cat_tec_444 SMALLINT DEFAULT 0,
    cat_tec_445 SMALLINT DEFAULT 0, cat_tec_446 SMALLINT DEFAULT 0, cat_tec_447 SMALLINT DEFAULT 0, cat_tec_448 SMALLINT DEFAULT 0, cat_tec_449 SMALLINT DEFAULT 0,
    cat_tec_450 SMALLINT DEFAULT 0, cat_tec_451 SMALLINT DEFAULT 0, cat_tec_452 SMALLINT DEFAULT 0, cat_tec_453 SMALLINT DEFAULT 0, cat_tec_454 SMALLINT DEFAULT 0,
    cat_tec_455 SMALLINT DEFAULT 0, cat_tec_456 SMALLINT DEFAULT 0, cat_tec_457 SMALLINT DEFAULT 0, cat_tec_458 SMALLINT DEFAULT 0, cat_tec_459 SMALLINT DEFAULT 0,
    cat_tec_460 SMALLINT DEFAULT 0, cat_tec_461 SMALLINT DEFAULT 0, cat_tec_462 SMALLINT DEFAULT 0, cat_tec_463 SMALLINT DEFAULT 0, cat_tec_464 SMALLINT DEFAULT 0,
    cat_tec_465 SMALLINT DEFAULT 0, cat_tec_466 SMALLINT DEFAULT 0, cat_tec_467 SMALLINT DEFAULT 0, cat_tec_468 SMALLINT DEFAULT 0, cat_tec_469 SMALLINT DEFAULT 0,
    cat_tec_470 SMALLINT DEFAULT 0, cat_tec_471 SMALLINT DEFAULT 0, cat_tec_472 SMALLINT DEFAULT 0, cat_tec_473 SMALLINT DEFAULT 0, cat_tec_474 SMALLINT DEFAULT 0,
    cat_tec_475 SMALLINT DEFAULT 0, cat_tec_476 SMALLINT DEFAULT 0, cat_tec_477 SMALLINT DEFAULT 0, cat_tec_478 SMALLINT DEFAULT 0, cat_tec_479 SMALLINT DEFAULT 0,
    cat_tec_480 SMALLINT DEFAULT 0, cat_tec_481 SMALLINT DEFAULT 0, cat_tec_482 SMALLINT DEFAULT 0, cat_tec_483 SMALLINT DEFAULT 0, cat_tec_484 SMALLINT DEFAULT 0,
    cat_tec_485 SMALLINT DEFAULT 0, cat_tec_486 SMALLINT DEFAULT 0, cat_tec_487 SMALLINT DEFAULT 0, cat_tec_488 SMALLINT DEFAULT 0, cat_tec_489 SMALLINT DEFAULT 0,
    cat_tec_490 SMALLINT DEFAULT 0, cat_tec_491 SMALLINT DEFAULT 0, cat_tec_492 SMALLINT DEFAULT 0, cat_tec_493 SMALLINT DEFAULT 0, cat_tec_494 SMALLINT DEFAULT 0,
    cat_tec_495 SMALLINT DEFAULT 0, cat_tec_496 SMALLINT DEFAULT 0, cat_tec_497 SMALLINT DEFAULT 0, cat_tec_498 SMALLINT DEFAULT 0, cat_tec_499 SMALLINT DEFAULT 0,
    cat_tec_500 SMALLINT DEFAULT 0, cat_tec_501 SMALLINT DEFAULT 0, cat_tec_502 SMALLINT DEFAULT 0, cat_tec_503 SMALLINT DEFAULT 0, cat_tec_504 SMALLINT DEFAULT 0,
    cat_tec_505 SMALLINT DEFAULT 0, cat_tec_506 SMALLINT DEFAULT 0, cat_tec_507 SMALLINT DEFAULT 0, cat_tec_508 SMALLINT DEFAULT 0, cat_tec_509 SMALLINT DEFAULT 0,
    cat_tec_510 SMALLINT DEFAULT 0, cat_tec_511 SMALLINT DEFAULT 0, cat_tec_512 SMALLINT DEFAULT 0, cat_tec_513 SMALLINT DEFAULT 0, cat_tec_514 SMALLINT DEFAULT 0,
    cat_tec_515 SMALLINT DEFAULT 0, cat_tec_516 SMALLINT DEFAULT 0, cat_tec_517 SMALLINT DEFAULT 0, cat_tec_518 SMALLINT DEFAULT 0, cat_tec_519 SMALLINT DEFAULT 0,
    cat_tec_520 SMALLINT DEFAULT 0, cat_tec_521 SMALLINT DEFAULT 0, cat_tec_522 SMALLINT DEFAULT 0, cat_tec_523 SMALLINT DEFAULT 0, cat_tec_524 SMALLINT DEFAULT 0,
    cat_tec_525 SMALLINT DEFAULT 0, cat_tec_526 SMALLINT DEFAULT 0, cat_tec_527 SMALLINT DEFAULT 0, cat_tec_528 SMALLINT DEFAULT 0, cat_tec_529 SMALLINT DEFAULT 0,
    cat_tec_530 SMALLINT DEFAULT 0, cat_tec_531 SMALLINT DEFAULT 0, cat_tec_532 SMALLINT DEFAULT 0, cat_tec_533 SMALLINT DEFAULT 0, cat_tec_534 SMALLINT DEFAULT 0,
    cat_tec_535 SMALLINT DEFAULT 0, cat_tec_536 SMALLINT DEFAULT 0, cat_tec_537 SMALLINT DEFAULT 0, cat_tec_538 SMALLINT DEFAULT 0, cat_tec_539 SMALLINT DEFAULT 0,
    cat_tec_540 SMALLINT DEFAULT 0, cat_tec_541 SMALLINT DEFAULT 0, cat_tec_542 SMALLINT DEFAULT 0, cat_tec_543 SMALLINT DEFAULT 0, cat_tec_544 SMALLINT DEFAULT 0,
    cat_tec_545 SMALLINT DEFAULT 0, cat_tec_546 SMALLINT DEFAULT 0, cat_tec_547 SMALLINT DEFAULT 0, cat_tec_548 SMALLINT DEFAULT 0, cat_tec_549 SMALLINT DEFAULT 0,
    cat_tec_550 SMALLINT DEFAULT 0, cat_tec_551 SMALLINT DEFAULT 0, cat_tec_552 SMALLINT DEFAULT 0, cat_tec_553 SMALLINT DEFAULT 0, cat_tec_554 SMALLINT DEFAULT 0,
    cat_tec_555 SMALLINT DEFAULT 0, cat_tec_556 SMALLINT DEFAULT 0, cat_tec_557 SMALLINT DEFAULT 0, cat_tec_558 SMALLINT DEFAULT 0, cat_tec_559 SMALLINT DEFAULT 0,
    cat_tec_560 SMALLINT DEFAULT 0, cat_tec_561 SMALLINT DEFAULT 0, cat_tec_562 SMALLINT DEFAULT 0, cat_tec_563 SMALLINT DEFAULT 0, cat_tec_564 SMALLINT DEFAULT 0,
    cat_tec_565 SMALLINT DEFAULT 0, cat_tec_566 SMALLINT DEFAULT 0, cat_tec_567 SMALLINT DEFAULT 0, cat_tec_568 SMALLINT DEFAULT 0, cat_tec_569 SMALLINT DEFAULT 0,
    cat_tec_570 SMALLINT DEFAULT 0, cat_tec_571 SMALLINT DEFAULT 0, cat_tec_572 SMALLINT DEFAULT 0, cat_tec_573 SMALLINT DEFAULT 0, cat_tec_574 SMALLINT DEFAULT 0,
    cat_tec_575 SMALLINT DEFAULT 0, cat_tec_576 SMALLINT DEFAULT 0, cat_tec_577 SMALLINT DEFAULT 0, cat_tec_578 SMALLINT DEFAULT 0, cat_tec_579 SMALLINT DEFAULT 0,
    cat_tec_580 SMALLINT DEFAULT 0, cat_tec_581 SMALLINT DEFAULT 0, cat_tec_582 SMALLINT DEFAULT 0, cat_tec_583 SMALLINT DEFAULT 0, cat_tec_584 SMALLINT DEFAULT 0,
    cat_tec_585 SMALLINT DEFAULT 0, cat_tec_586 SMALLINT DEFAULT 0, cat_tec_587 SMALLINT DEFAULT 0, cat_tec_588 SMALLINT DEFAULT 0, cat_tec_589 SMALLINT DEFAULT 0,
    cat_tec_590 SMALLINT DEFAULT 0, cat_tec_591 SMALLINT DEFAULT 0, cat_tec_592 SMALLINT DEFAULT 0, cat_tec_593 SMALLINT DEFAULT 0, cat_tec_594 SMALLINT DEFAULT 0,
    cat_tec_595 SMALLINT DEFAULT 0, cat_tec_596 SMALLINT DEFAULT 0, cat_tec_597 SMALLINT DEFAULT 0, cat_tec_598 SMALLINT DEFAULT 0, cat_tec_599 SMALLINT DEFAULT 0,
    cat_tec_600 SMALLINT DEFAULT 0, cat_tec_601 SMALLINT DEFAULT 0, cat_tec_602 SMALLINT DEFAULT 0, cat_tec_603 SMALLINT DEFAULT 0, cat_tec_604 SMALLINT DEFAULT 0,
    cat_tec_605 SMALLINT DEFAULT 0, cat_tec_606 SMALLINT DEFAULT 0, cat_tec_607 SMALLINT DEFAULT 0, cat_tec_608 SMALLINT DEFAULT 0, cat_tec_609 SMALLINT DEFAULT 0,
    cat_tec_610 SMALLINT DEFAULT 0, cat_tec_611 SMALLINT DEFAULT 0, cat_tec_612 SMALLINT DEFAULT 0, cat_tec_613 SMALLINT DEFAULT 0, cat_tec_614 SMALLINT DEFAULT 0,
    cat_tec_615 SMALLINT DEFAULT 0, cat_tec_616 SMALLINT DEFAULT 0, cat_tec_617 SMALLINT DEFAULT 0, cat_tec_618 SMALLINT DEFAULT 0, cat_tec_619 SMALLINT DEFAULT 0,
    cat_tec_620 SMALLINT DEFAULT 0, cat_tec_621 SMALLINT DEFAULT 0, cat_tec_622 SMALLINT DEFAULT 0, cat_tec_623 SMALLINT DEFAULT 0, cat_tec_624 SMALLINT DEFAULT 0,
    cat_tec_625 SMALLINT DEFAULT 0, cat_tec_626 SMALLINT DEFAULT 0, cat_tec_627 SMALLINT DEFAULT 0, cat_tec_628 SMALLINT DEFAULT 0, cat_tec_629 SMALLINT DEFAULT 0,
    cat_tec_630 SMALLINT DEFAULT 0, cat_tec_631 SMALLINT DEFAULT 0, cat_tec_632 SMALLINT DEFAULT 0, cat_tec_633 SMALLINT DEFAULT 0, cat_tec_634 SMALLINT DEFAULT 0,
    cat_tec_635 SMALLINT DEFAULT 0, cat_tec_636 SMALLINT DEFAULT 0, cat_tec_637 SMALLINT DEFAULT 0, cat_tec_638 SMALLINT DEFAULT 0, cat_tec_639 SMALLINT DEFAULT 0,
    cat_tec_640 SMALLINT DEFAULT 0, cat_tec_641 SMALLINT DEFAULT 0, cat_tec_642 SMALLINT DEFAULT 0, cat_tec_643 SMALLINT DEFAULT 0, cat_tec_644 SMALLINT DEFAULT 0,
    cat_tec_645 SMALLINT DEFAULT 0, cat_tec_646 SMALLINT DEFAULT 0, cat_tec_647 SMALLINT DEFAULT 0, cat_tec_648 SMALLINT DEFAULT 0, cat_tec_649 SMALLINT DEFAULT 0,
    cat_tec_650 SMALLINT DEFAULT 0, cat_tec_651 SMALLINT DEFAULT 0, cat_tec_652 SMALLINT DEFAULT 0, cat_tec_653 SMALLINT DEFAULT 0, cat_tec_654 SMALLINT DEFAULT 0,
    cat_tec_655 SMALLINT DEFAULT 0, cat_tec_656 SMALLINT DEFAULT 0, cat_tec_657 SMALLINT DEFAULT 0, cat_tec_658 SMALLINT DEFAULT 0, cat_tec_659 SMALLINT DEFAULT 0,
    cat_tec_660 SMALLINT DEFAULT 0, cat_tec_661 SMALLINT DEFAULT 0, cat_tec_662 SMALLINT DEFAULT 0, cat_tec_663 SMALLINT DEFAULT 0, cat_tec_664 SMALLINT DEFAULT 0,
    cat_tec_665 SMALLINT DEFAULT 0, cat_tec_666 SMALLINT DEFAULT 0, cat_tec_667 SMALLINT DEFAULT 0, cat_tec_668 SMALLINT DEFAULT 0, cat_tec_669 SMALLINT DEFAULT 0,
    cat_tec_670 SMALLINT DEFAULT 0, cat_tec_671 SMALLINT DEFAULT 0, cat_tec_672 SMALLINT DEFAULT 0, cat_tec_673 SMALLINT DEFAULT 0, cat_tec_674 SMALLINT DEFAULT 0,
    cat_tec_675 SMALLINT DEFAULT 0, cat_tec_676 SMALLINT DEFAULT 0, cat_tec_677 SMALLINT DEFAULT 0, cat_tec_678 SMALLINT DEFAULT 0, cat_tec_679 SMALLINT DEFAULT 0,
    cat_tec_680 SMALLINT DEFAULT 0, cat_tec_681 SMALLINT DEFAULT 0, cat_tec_682 SMALLINT DEFAULT 0, cat_tec_683 SMALLINT DEFAULT 0, cat_tec_684 SMALLINT DEFAULT 0,
    cat_tec_685 SMALLINT DEFAULT 0, cat_tec_686 SMALLINT DEFAULT 0, cat_tec_687 SMALLINT DEFAULT 0, cat_tec_688 SMALLINT DEFAULT 0, cat_tec_689 SMALLINT DEFAULT 0,
    cat_tec_690 SMALLINT DEFAULT 0, cat_tec_691 SMALLINT DEFAULT 0, cat_tec_692 SMALLINT DEFAULT 0, cat_tec_693 SMALLINT DEFAULT 0, cat_tec_694 SMALLINT DEFAULT 0,
    cat_tec_695 SMALLINT DEFAULT 0, cat_tec_696 SMALLINT DEFAULT 0, cat_tec_697 SMALLINT DEFAULT 0, cat_tec_698 SMALLINT DEFAULT 0, cat_tec_699 SMALLINT DEFAULT 0,
    cat_tec_700 SMALLINT DEFAULT 0, cat_tec_701 SMALLINT DEFAULT 0, cat_tec_702 SMALLINT DEFAULT 0, cat_tec_703 SMALLINT DEFAULT 0, cat_tec_704 SMALLINT DEFAULT 0,
    cat_tec_705 SMALLINT DEFAULT 0, cat_tec_706 SMALLINT DEFAULT 0, cat_tec_707 SMALLINT DEFAULT 0, cat_tec_708 SMALLINT DEFAULT 0, cat_tec_709 SMALLINT DEFAULT 0,
    cat_tec_710 SMALLINT DEFAULT 0, cat_tec_711 SMALLINT DEFAULT 0, cat_tec_712 SMALLINT DEFAULT 0, cat_tec_713 SMALLINT DEFAULT 0, cat_tec_714 SMALLINT DEFAULT 0,
    cat_tec_715 SMALLINT DEFAULT 0, cat_tec_716 SMALLINT DEFAULT 0, cat_tec_717 SMALLINT DEFAULT 0, cat_tec_718 SMALLINT DEFAULT 0, cat_tec_719 SMALLINT DEFAULT 0,
    cat_tec_720 SMALLINT DEFAULT 0, cat_tec_721 SMALLINT DEFAULT 0, cat_tec_722 SMALLINT DEFAULT 0, cat_tec_723 SMALLINT DEFAULT 0, cat_tec_724 SMALLINT DEFAULT 0,
    cat_tec_725 SMALLINT DEFAULT 0, cat_tec_726 SMALLINT DEFAULT 0, cat_tec_727 SMALLINT DEFAULT 0, cat_tec_728 SMALLINT DEFAULT 0, cat_tec_729 SMALLINT DEFAULT 0,
    cat_tec_730 SMALLINT DEFAULT 0, cat_tec_731 SMALLINT DEFAULT 0, cat_tec_732 SMALLINT DEFAULT 0, cat_tec_733 SMALLINT DEFAULT 0, cat_tec_734 SMALLINT DEFAULT 0,
    cat_tec_735 SMALLINT DEFAULT 0, cat_tec_736 SMALLINT DEFAULT 0, cat_tec_737 SMALLINT DEFAULT 0, cat_tec_738 SMALLINT DEFAULT 0, cat_tec_739 SMALLINT DEFAULT 0,
    cat_tec_740 SMALLINT DEFAULT 0, cat_tec_741 SMALLINT DEFAULT 0, cat_tec_742 SMALLINT DEFAULT 0, cat_tec_743 SMALLINT DEFAULT 0, cat_tec_744 SMALLINT DEFAULT 0,
    cat_tec_745 SMALLINT DEFAULT 0, cat_tec_746 SMALLINT DEFAULT 0, cat_tec_747 SMALLINT DEFAULT 0, cat_tec_748 SMALLINT DEFAULT 0, cat_tec_749 SMALLINT DEFAULT 0,
    cat_tec_750 SMALLINT DEFAULT 0, cat_tec_751 SMALLINT DEFAULT 0, cat_tec_752 SMALLINT DEFAULT 0, cat_tec_753 SMALLINT DEFAULT 0, cat_tec_754 SMALLINT DEFAULT 0,
    cat_tec_755 SMALLINT DEFAULT 0, cat_tec_756 SMALLINT DEFAULT 0, cat_tec_757 SMALLINT DEFAULT 0, cat_tec_758 SMALLINT DEFAULT 0, cat_tec_759 SMALLINT DEFAULT 0,
    cat_tec_760 SMALLINT DEFAULT 0, cat_tec_761 SMALLINT DEFAULT 0, cat_tec_762 SMALLINT DEFAULT 0, cat_tec_763 SMALLINT DEFAULT 0, cat_tec_764 SMALLINT DEFAULT 0,
    cat_tec_765 SMALLINT DEFAULT 0, cat_tec_766 SMALLINT DEFAULT 0, cat_tec_767 SMALLINT DEFAULT 0, cat_tec_768 SMALLINT DEFAULT 0, cat_tec_769 SMALLINT DEFAULT 0,
    cat_tec_770 SMALLINT DEFAULT 0, cat_tec_771 SMALLINT DEFAULT 0, cat_tec_772 SMALLINT DEFAULT 0, cat_tec_773 SMALLINT DEFAULT 0, cat_tec_774 SMALLINT DEFAULT 0,
    cat_tec_775 SMALLINT DEFAULT 0, cat_tec_776 SMALLINT DEFAULT 0, cat_tec_777 SMALLINT DEFAULT 0, cat_tec_778 SMALLINT DEFAULT 0, cat_tec_779 SMALLINT DEFAULT 0,
    cat_tec_780 SMALLINT DEFAULT 0, cat_tec_781 SMALLINT DEFAULT 0, cat_tec_782 SMALLINT DEFAULT 0, cat_tec_783 SMALLINT DEFAULT 0, cat_tec_784 SMALLINT DEFAULT 0,
    cat_tec_785 SMALLINT DEFAULT 0, cat_tec_786 SMALLINT DEFAULT 0, cat_tec_787 SMALLINT DEFAULT 0, cat_tec_788 SMALLINT DEFAULT 0, cat_tec_789 SMALLINT DEFAULT 0,
    cat_tec_790 SMALLINT DEFAULT 0, cat_tec_791 SMALLINT DEFAULT 0, cat_tec_792 SMALLINT DEFAULT 0, cat_tec_793 SMALLINT DEFAULT 0, cat_tec_794 SMALLINT DEFAULT 0,
    cat_tec_795 SMALLINT DEFAULT 0, cat_tec_796 SMALLINT DEFAULT 0, cat_tec_797 SMALLINT DEFAULT 0, cat_tec_798 SMALLINT DEFAULT 0, cat_tec_799 SMALLINT DEFAULT 0,
    cat_tec_800 SMALLINT DEFAULT 0, cat_tec_801 SMALLINT DEFAULT 0, cat_tec_802 SMALLINT DEFAULT 0, cat_tec_803 SMALLINT DEFAULT 0, cat_tec_804 SMALLINT DEFAULT 0,
    cat_tec_805 SMALLINT DEFAULT 0, cat_tec_806 SMALLINT DEFAULT 0, cat_tec_807 SMALLINT DEFAULT 0, cat_tec_808 SMALLINT DEFAULT 0, cat_tec_809 SMALLINT DEFAULT 0,
    cat_tec_810 SMALLINT DEFAULT 0, cat_tec_811 SMALLINT DEFAULT 0, cat_tec_812 SMALLINT DEFAULT 0, cat_tec_813 SMALLINT DEFAULT 0, cat_tec_814 SMALLINT DEFAULT 0,
    cat_tec_815 SMALLINT DEFAULT 0, cat_tec_816 SMALLINT DEFAULT 0, cat_tec_817 SMALLINT DEFAULT 0, cat_tec_818 SMALLINT DEFAULT 0, cat_tec_819 SMALLINT DEFAULT 0,
    cat_tec_820 SMALLINT DEFAULT 0, cat_tec_821 SMALLINT DEFAULT 0, cat_tec_822 SMALLINT DEFAULT 0, cat_tec_823 SMALLINT DEFAULT 0, cat_tec_824 SMALLINT DEFAULT 0,
    cat_tec_825 SMALLINT DEFAULT 0, cat_tec_826 SMALLINT DEFAULT 0, cat_tec_827 SMALLINT DEFAULT 0, cat_tec_828 SMALLINT DEFAULT 0, cat_tec_829 SMALLINT DEFAULT 0,
    cat_tec_830 SMALLINT DEFAULT 0, cat_tec_831 SMALLINT DEFAULT 0, cat_tec_832 SMALLINT DEFAULT 0, cat_tec_833 SMALLINT DEFAULT 0, cat_tec_834 SMALLINT DEFAULT 0,
    cat_tec_835 SMALLINT DEFAULT 0, cat_tec_836 SMALLINT DEFAULT 0, cat_tec_837 SMALLINT DEFAULT 0, cat_tec_838 SMALLINT DEFAULT 0, cat_tec_839 SMALLINT DEFAULT 0,
    cat_tec_840 SMALLINT DEFAULT 0, cat_tec_841 SMALLINT DEFAULT 0, cat_tec_842 SMALLINT DEFAULT 0, cat_tec_843 SMALLINT DEFAULT 0, cat_tec_844 SMALLINT DEFAULT 0,
    cat_tec_845 SMALLINT DEFAULT 0, cat_tec_846 SMALLINT DEFAULT 0
);

-- Add remaining categorical columns via ALTER TABLE to keep file manageable
-- (In practice, copy full column list from edop_matrix_schema.sql)

-- Simplified: Include key categorical columns only, rest added via script
-- Full column set would be copied from edop_matrix_schema.sql

COMMENT ON TABLE whc_matrix IS 'Environmental signature matrix for 258 WHC cities. Same structure as edop_matrix but references wh_cities.';

--------------------------------------------------------------------------------
-- 2. PCA Coordinates (up to 50 components for 254 samples)
--------------------------------------------------------------------------------
CREATE TABLE whc_pca_coords (
    city_id INTEGER PRIMARY KEY REFERENCES wh_cities(id),
    pc1 DOUBLE PRECISION, pc2 DOUBLE PRECISION, pc3 DOUBLE PRECISION, pc4 DOUBLE PRECISION, pc5 DOUBLE PRECISION,
    pc6 DOUBLE PRECISION, pc7 DOUBLE PRECISION, pc8 DOUBLE PRECISION, pc9 DOUBLE PRECISION, pc10 DOUBLE PRECISION,
    pc11 DOUBLE PRECISION, pc12 DOUBLE PRECISION, pc13 DOUBLE PRECISION, pc14 DOUBLE PRECISION, pc15 DOUBLE PRECISION,
    pc16 DOUBLE PRECISION, pc17 DOUBLE PRECISION, pc18 DOUBLE PRECISION, pc19 DOUBLE PRECISION, pc20 DOUBLE PRECISION,
    pc21 DOUBLE PRECISION, pc22 DOUBLE PRECISION, pc23 DOUBLE PRECISION, pc24 DOUBLE PRECISION, pc25 DOUBLE PRECISION,
    pc26 DOUBLE PRECISION, pc27 DOUBLE PRECISION, pc28 DOUBLE PRECISION, pc29 DOUBLE PRECISION, pc30 DOUBLE PRECISION,
    pc31 DOUBLE PRECISION, pc32 DOUBLE PRECISION, pc33 DOUBLE PRECISION, pc34 DOUBLE PRECISION, pc35 DOUBLE PRECISION,
    pc36 DOUBLE PRECISION, pc37 DOUBLE PRECISION, pc38 DOUBLE PRECISION, pc39 DOUBLE PRECISION, pc40 DOUBLE PRECISION,
    pc41 DOUBLE PRECISION, pc42 DOUBLE PRECISION, pc43 DOUBLE PRECISION, pc44 DOUBLE PRECISION, pc45 DOUBLE PRECISION,
    pc46 DOUBLE PRECISION, pc47 DOUBLE PRECISION, pc48 DOUBLE PRECISION, pc49 DOUBLE PRECISION, pc50 DOUBLE PRECISION
);

COMMENT ON TABLE whc_pca_coords IS 'PCA coordinates for WH cities (50 components max)';

--------------------------------------------------------------------------------
-- 3. PCA Variance
--------------------------------------------------------------------------------
CREATE TABLE whc_pca_variance (
    component INTEGER PRIMARY KEY,
    explained_variance DOUBLE PRECISION,
    explained_ratio DOUBLE PRECISION,
    cumulative_ratio DOUBLE PRECISION
);

COMMENT ON TABLE whc_pca_variance IS 'Explained variance for each principal component';

--------------------------------------------------------------------------------
-- 4. Similarity Matrix
--------------------------------------------------------------------------------
CREATE TABLE whc_similarity (
    city_a INTEGER REFERENCES wh_cities(id),
    city_b INTEGER REFERENCES wh_cities(id),
    distance DOUBLE PRECISION,
    similarity DOUBLE PRECISION,  -- 1 / (1 + distance)
    PRIMARY KEY (city_a, city_b)
);

CREATE INDEX idx_whc_similarity_a ON whc_similarity(city_a);
CREATE INDEX idx_whc_similarity_b ON whc_similarity(city_b);

COMMENT ON TABLE whc_similarity IS 'Pairwise Euclidean distances in PCA space between WH cities';

--------------------------------------------------------------------------------
-- 5. Cluster Assignments
--------------------------------------------------------------------------------
CREATE TABLE whc_clusters (
    city_id INTEGER PRIMARY KEY REFERENCES wh_cities(id),
    cluster_id INTEGER NOT NULL,
    cluster_label TEXT,
    distance_to_centroid DOUBLE PRECISION
);

CREATE INDEX idx_whc_clusters_cluster ON whc_clusters(cluster_id);

COMMENT ON TABLE whc_clusters IS 'K-means cluster assignments for WH cities';
